

const arr = [
    "In the Victorian era, people used to take photos of their dead relatives in lifelike poses as mementos.",
    "A single human corpse can release over 200 toxic chemicals as it decomposes.",
    "Many ancient cultures believed mirrors were gateways to the supernatural, trapping spirits or even your own soul.",
    "Sleep paralysis is when your brain wakes up but your body is still asleep, often leading to terrifying hallucinations of dark figures.",
    "There’s a phenomenon called ‘The Hum’ that only some people can hear – it’s a low-frequency noise that has no known source.",
    "After death, the body can still move slightly as muscles contract and decompose.",
    "The average person walks by at least 16 murderers in their lifetime.",
    "Around 20% of children report having seen or heard ghosts, especially in older houses.",
    "In the 1500s, people believed cats were witches' familiars, leading to massive cat killings that may have worsened the spread of the Black Plague.",
    "Dead bodies can twitch for hours after death due to remaining electrical activity in muscle cells.",
    "Dolls were once thought to house spirits, leading to the creation of ventriloquist dolls and haunting tales of possessed toys.",
    "There are certain insects that can survive without their heads for weeks, such as cockroaches.",
    "In some cultures, people would bury their loved ones with a bell above ground, just in case they were buried alive.",
    "The 'Mandela Effect' is a phenomenon where a large group of people remember something differently than how it happened, leading some to believe in alternate realities.",
    "Morgues sometimes place bodies in 'warm chambers' because extremely low temperatures can lead to unexpected muscle contractions, causing bodies to 'sit up'.",
    "Humans shed around 1.5 pounds of skin each year – much of the dust in your home is actually dead skin cells.",
    "A parasite called Toxoplasma gondii, commonly found in cat feces, can alter a human’s brain and potentially increase risky behavior.",
    "People have been known to wake up during surgery due to anesthesia awareness, experiencing every sensation without being able to move.",
    "Ancient Egyptians believed in ‘shadow people,’ spirits of the deceased lurking in the world of the living.",
    "There is a rare condition called Cotard's Syndrome, where people believe they are dead or decomposing.",
    "Human teeth remain after everything else decomposes, which is why dental records are used to identify remains.",
    "Victorians used to believe that if you left a window open after someone died, their soul would escape.",
    "The average person dreams about 5 people they know dying in their lifetime.",
    "Some graves have iron cages over them, placed there to stop the dead from rising back up.",
    "There are over 250,000 sweat glands on your feet, which attract bacteria that create the smell.",
    "During sleep paralysis, some people report seeing shadowy figures watching them from the corner of their room.",
    "Thousands of people go missing every year, with many cases remaining unsolved.",
    "When you die, your hearing is often the last sense to go.",
    "Body farms study human decomposition in open-air environments for forensic research.",
    "Every two minutes, someone dies from a snake bite somewhere in the world.",
    "There are more vacant houses in the U.S. than there are homeless people.",
    "After decapitation, a human head can remain conscious for a few seconds.",
    "Some people have a rare psychological condition where they believe they’re turning into an animal, known as clinical lycanthropy.",
    "Dogs are often said to bark or act agitated when they sense a supernatural presence.",
    "Over 300 million people suffer from parasomnia, a sleep disorder causing them to act out violent dreams.",
    "The Japanese believe spirits live in everyday objects, called 'tsukumogami,' which come alive after 100 years.",
    "In medieval Europe, graveyards were often reused, and bodies were dug up and reburied or even ground into dust to make room for new burials.",
    "Ancient Romans feared the restless spirits of those who had been wronged in life, which they called ‘lemures.’",
    "There is a rare disease called fatal familial insomnia that causes a person to eventually lose the ability to sleep entirely, leading to death.",
    "Some people suffer from ‘exploding head syndrome,’ hearing loud explosions or crashes as they’re about to fall asleep.",
    "During the Victorian era, people held seances and took photos claiming to capture ghosts.",
    "The Wendigo is a mythical creature said to be created when a human resorts to cannibalism.",
    "In some forests, trees can communicate distress signals to each other through their roots.",
    "Some cultures believe taking a photo steals a part of your soul.",
    "Over 90% of the ocean remains unexplored, leaving countless creatures undiscovered.",
    "In 1918, hundreds of people dropped dead while laughing due to the Spanish Flu.",
    "Voodoo dolls were believed to allow one to inflict harm on another person from afar.",
    "In places like New Orleans, people still practice voodoo and believe in powerful curses and spirits.",
    "Some old prisons were designed with specific torture cells, such as “The Pit,” designed to drive people mad.",
    "The fear of clowns, called coulrophobia, is believed to stem from their unnatural painted faces and exaggerated features.",
    "An estimated 10% of Americans believe they've encountered a ghost.",
    "Dead bodies can sometimes emit a corpse wax called adipocere, which preserves them for decades.",
    "Some buildings are claimed to be ‘vortexes’ that increase paranormal activity.",
    "Human remains have been found at the bottom of the catacombs in Paris, which stretch for miles under the city.",
    "The fear of being buried alive was so common that 'safety coffins' were invented, which allowed people to ring a bell from underground.",
    "Scotland’s Greyfriars Kirkyard is reportedly one of the most haunted cemeteries in the world.",
    "In the past, people with mental illnesses were often locked away in asylums, where they faced horrific treatments.",
    "Some funeral homes offer mummification services, preserving bodies in a way similar to ancient Egyptians.",
    "There’s a phenomenon known as ‘phantom limb pain,’ where amputees feel pain or sensation in their missing limbs.",
    "A body can take up to 100 years to fully decompose if buried in a coffin.",
    "The phrase ‘saved by the bell’ is believed to come from people who were buried alive and used a bell to signal for help.",
    "Many shipwrecks remain lost and undiscovered under the sea, carrying mysteries from long ago.",
    "Certain abandoned hospitals and asylums are said to be haunted by the spirits of past patients.",
    "If you cover a mirror while someone is dying, it’s believed it will trap their spirit.",
    "Some believe spirits can attach to objects and haunt those who own them.",
    "The 'Devil’s Bible' is one of the largest surviving medieval manuscripts, supposedly written with the help of Satan.",
    "In the 1920s, radium was used in paint for watches, leading to fatal radiation exposure for factory workers.",
    "A dead body can swell to twice its normal size due to gas buildup during decomposition.",
    "The fear of spiders, or arachnophobia, affects about 10% of the population, possibly stemming from evolutionary fear.",
    "In the past, people believed certain mountain ranges were inhabited by supernatural beings.",
    "Human bodies can sometimes produce a chemical glow after death, known as bioluminescence.",
    "Ancient Egyptian curses were written on tombs to ward off grave robbers.",
    "In some countries, there's a tradition to place coins on the eyes of the deceased to pay the ferryman for passage to the afterlife.",
    "Plague doctors in medieval Europe wore masks with beaks, believing it would filter the air and prevent illness.",
    "A person’s hair and nails may appear to grow after death as the skin retracts.",
    "Cemeteries were often located far from cities to prevent the spread of disease from decaying bodies.",
    "There are reports of entire towns or villages being abandoned suddenly with no explanation.",
    "Certain flowers, like lilies, are associated with death and are commonly placed in funeral homes.",
    "The sound of footsteps in an empty hallway is one of the most common paranormal phenomena reported worldwide.",
    "Some believe that orbs seen in photos are spirits, caught on camera as floating lights.",
    "Throughout history, there have been reports of people being buried with valuable items, leading to grave robbing.",
    "Some forests, such as the Aokigahara Forest in Japan, are known for their high rates of suicides.",
    "Thousands of people suffer from ‘homicidal somnambulism,’ sleepwalking into dangerous or deadly situations.",
    "Certain parasites can actually control the behavior of their hosts, making them behave in unusual ways.",
    "Many ancient cultures left offerings at crossroads, believing they were haunted by spirits.",
    "Throughout history, people have been found mummified in bogs, their skin and hair perfectly preserved.",
    "In some cultures, it’s believed that whistling at night attracts evil spirits.",
    "Dead bodies often emit a unique, pungent odor as gases are released during decomposition.",
    "A fear called 'thalassophobia' is the fear of large bodies of water, stemming from the unknown lurking below.",
    "Some people suffer from the fear of long words, ironically called hippopotomonstrosesquipedaliophobia.",
    "There are over 40,000 abandoned towns in the U.S. alone, often considered to be haunted or cursed.",
    "There’s a phenomenon called ‘cemetery sickness,’ where people feel nauseous or dizzy in cemeteries.",
    "Human eyes remain intact longer than most other body parts after death.",
    "The sounds of distant screams are sometimes heard echoing through deep caves, known as ‘auditory hallucinations’ in quiet, echoing environments.",
    "There are real reports of people developing intense, irrational fears after traumatic experiences, like extreme claustrophobia."
];

function randnum(){
    return Math.floor(Math.random() * arr.length);
}

function showfact() {
    let num = randnum();
    console.log(num);
    document.getElementById("fact").textContent = arr[num];
}

